### ISSUE TITLE
Can't get Cura working for dual extruder

### ISSUE THREAD

**Issue by ppinto** [stuartpb/repligreater#1]
Hi Stuart,

Thanks for posting this information on Git for the qidi tech printer.  Your guide helped me get my printer working with Cura and it prints great.  The only issue I have is that no matter what I do, I can only get it to  print with the Right Extruder.  I have tried everything that I can think of, even changing the definition files that you provide but no go.  Closest I have come was getting the printer to heat the left extruder, but it still tried to print with a cold right extruder.  I am using Cura 3.2.1,  did you every get this to work?  Thanks in advance for any help that you can provide. 
-Phil

**Comment by stuartpb** [comment]
I was trying to print with Cura and any dual-extrusion prints I tried ended up failing (see the last paragraph [here](https://github.com/stuartpb/stuartpb.plan/blob/f1b298ae4a8b4870c9f22c9dcd712a6380940a0f/PLAN.md#3d-printing)). I intend to reach out to Qidi Tech support for help with this at some point soon.

I was able to switch extruders for a single-extruder print, though. Did you change the material for the object you're looking to print in Cura to the material of the appropriate extruder?

**Comment by ppinto** [comment]
Thanks again for the help.  I am only trying single extruder prints.  One wrinkle, I am printing from Cura through Octoprint.  The printer is attached to a Raspberry PI.  I have tried to set the active extruder from the panel on the right of the screen that shows the printer name, I think I have set the materials correctly.  Right now both left and right extruders have ABS loaded.  I have also tried to set the active extruder from the pull down menu.   From Octoprint I can manually control heat and force extrusion of material.  The left if Extruder 0 and the Right is extruder 1.  I think this is backwards in Cura.

**Comment by stuartpb** [comment]
> I am only trying single extruder prints. One wrinkle, I am printing from Cura through Octoprint. The printer is attached to a Raspberry PI.

This is how I did my prints too (the printer connected to a laptop running OctoPrint, separate from my desktop).

>  I have tried to set the active extruder from the panel on the right of the screen that shows the printer name, I think I have set the materials correctly. Right now both left and right extruders have ABS loaded. I have also tried to set the active extruder from the pull down menu.

To be clear, have you tried these buttons , which toggle the material for a model on the build plate? 
![image](https://user-images.githubusercontent.com/572196/39225189-c44672d8-47ff-11e8-9e4c-92bb85c18ece.png)

> The left if Extruder 0 and the Right is extruder 1. I think this is backwards in Cura.

If you're using the settings from https://github.com/stuartpb/repligreater/tree/master/settings/qidi-tech-i/cura, they'll be named as "Left Extruder" and "Right Extruder" in the UI, and, yes, the Left Extruder will be placed to the right of the Right Extruder, because the extruder with ID 0 is the Right Extruder and the extruder with ID 1 is the Left Extruder. (That's the way it is in the firmware and Cura doesn't have a way to renumber extruders just in the UI, so it's stuck like that.)

**Comment by ppinto** [comment]
You did it! - thank you.  I am not sure what I was setting in the interface, but your picture solved my problem.  The printer printed with the Left Extruder - Extruder Number 2 in Cura - Tool zero in Octoprint.  But the screen on the right where you select the material has extruder 1 and extruder 2, maybe that is just for defining what is in that extruder or not sure, I never noticed those icons on the left you pointed out.   

![cura_pics](https://user-images.githubusercontent.com/1489392/39281223-83896138-48d1-11e8-8ba1-373144066d66.jpg)

Thank you Stuart, I owe you one.  Or two, since I could not have gotten this to work without your initial work,  


Thanks...
-Phil
